- name: Install web server
  hosts: local
  become: true
  tasks:
  - name: Intalling the web service
    ansible.builtin.package:
      name: nginx
      state: present 
  - name: Enable to service
    ansible.builtin.service
      name: nginx
      state: enabled