- name: Check the user exist if not create a user
  hosts: local
  become: true
  tasks:
  - name: chekcing user if exist
    ansible.builtin.command: id expense
    register: USER
    ignore_errors: true

  - name: Check the user information
    ansible.builtin.debug:
      msg: "{{USER}}"

  - name: Create user
    ansible.builtin.command: useradd expense
    when: USER.rc != 0
