- name: Install multiple packages using LOOPS
  hosts: local
  become: true
  tasks: 
  - name: Using loops
    ansible.builtin.package:
      name: "{{item}}"
      state: present
    with_items: #with_items or loop. Either one will work for looping
    - mysql
    - nginx
    - httpd


    
