- name: create ec2-insances & R53 records for Expense project
  hosts: local
  connection: local
  vars:
  - VPC_ID: vpc-02311bb6ec227cbf5
  - AMI_ID: ami-09c813fb71547fc4f
  - SUBNET_ID: subnet-0d11182d94c27f1fd
  - SG_ID: sg-02220caccee1bf2cd
  tasks:
  - name: Create ec2-instances
    amazon.aws.ec2_instance:
      name: "{{item}}"
      instance_type: t3.micro
      image_id: "{{AMI_ID}}"
      region: us-east-1
      vpc_subnet_id: "{{SUBNET_ID}}"
      security_group: "{{SG_ID}}"
    loop:
    - mysql
    - backend
    - frontend
    register: ec2-instance

  - name: print the EC2 instances information
    ansible.builtin.debug:
      msg: "{{ec2-instace}}"